version: "3.7"
services:
  frappe:
    ports: !override
      - "127.0.0.1:8000:8000"
      - "127.0.0.1:9000:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    dns:
      - 8.8.8.8
    command: >
      bash -c "for i in $(seq 1 90); do getent hosts pypi.org >/dev/null 2>&1 && getent hosts api.github.com >/dev/null 2>&1 && break; echo 'Waiting for DNS...'; sleep 1; done; exec bash /workspace/init.sh"
    volumes:
      - .:/workspace
      - frappe-bench-data:/home/frappe
      - ../../frappe-custom/mmm_custom:/home/frappe/mmm_custom
      - ..:/home/frappe/crm
  redis:
    image: redis:7.2.4-alpine

volumes:
  frappe-bench-data:
